server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: productModule
        uri: http://localhost:8686
        predicates:
        - Path=/products/**
      - id: customerModule
        uri: http://localhost:8787
        predicates:
        - Path=/customer/**
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka